Added project from lesson OOP on 03/10/2017
DriesVuylsteke/TransitionAppliedInformatics pull request #1
Opened 2017-10-03 20:49 UTC by danielmertens

This is the first version of the project. I may still clean this up
later. The code and doc for the task we had to complete before the next lesson is also included.

2017-10-04 17:04 UTC, DriesVuylsteke commented
I have a couple suggestions before merging:

- This lecture was about writing documentation for methods using the post and effect annotations. To keep the project to the point please only include the classes built during the lecture. 
- A readme file can be supplied to give instructions on how to generate the documentation. 
- Don't use spaces in your path (Objectgeorienteerd programmeren -> oop)

2017-10-04 17:07 UTC, DriesVuylsteke requested changes
I have a couple suggestions before merging:

- This lecture was about writing documentation for methods using the post and effect annotations. To keep the project to the point please only include the classes built during the lecture.
- A readme file can be supplied to give instructions on how to generate the documentation.
- Don't use spaces in your path (Objectgeorienteerd programmeren -> oop)

2017-10-05 09:29 UTC, danielmertens reviewed
Requested changes implemented.

2017-10-06 13:06 UTC, DriesVuylsteke approved these changes

2017-10-06 13:07 UTC, merged